const colors = {
  light: {
    text: "#0B0C10",
    tint: "#7C6FF7",
    background: "#F5F5F8",
    foreground: "#0B0C10",
    card: "#FFFFFF",
    cardForeground: "#0B0C10",
    primary: "#7C6FF7",
    primaryForeground: "#FFFFFF",
    secondary: "#EDEDF5",
    secondaryForeground: "#3A3A4A",
    muted: "#EDEDF5",
    mutedForeground: "#8A8D9F",
    accent: "#F7386F",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0EC",
    input: "#E0E0EC",
    success: "#22C55E",
    twitter: "#1DA1F2",
    instagram: "#E1306C",
    facebook: "#1877F2",
    linkedin: "#0A66C2",
    tiktok: "#FF0050",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#9D97F9",
    background: "#0B0C10",
    foreground: "#FFFFFF",
    card: "#1A1B20",
    cardForeground: "#FFFFFF",
    primary: "#7C6FF7",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1F28",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1F28",
    mutedForeground: "#8A8D9F",
    accent: "#F7386F",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2B35",
    input: "#2A2B35",
    success: "#22C55E",
    twitter: "#1DA1F2",
    instagram: "#E1306C",
    facebook: "#1877F2",
    linkedin: "#0A66C2",
    tiktok: "#FF0050",
  },
  radius: 12,
};

export default colors;
